# Generated by Django 5.2.3 on 2025-06-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_bookmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='author',
        ),
    ]
